In [1]:
import torch

In [10]:
x = torch.tensor([[0,1],
                  [2,3],
                  [4,5]])

In [11]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [15]:
torch.movedim(x, 1, 0)

tensor([[0, 2, 4],
        [1, 3, 5]])

In [13]:
x.T

tensor([[0, 2, 4],
        [1, 3, 5]])