In [1]:
import torch

In [2]:
x = torch.ones([2,2], requires_grad=True)

In [5]:
print(x.data)

tensor([[1., 1.],
        [1., 1.]])


In [6]:
print(x.grad)

None


In [7]:
print(x.grad_fn)

None


In [8]:
y = x + 2

In [9]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [10]:
print(y.grad_fn)

In [11]:
z = y * y * 3
out = z.mean()

In [14]:
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [15]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [16]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [17]:
out.backward()

In [18]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [19]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
y.backward(torch.ones(2, 2), retain_graph=True)
# the retain_variables flag will prevent the internal buffers from being freed
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [20]:
z = y * y
print(z)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)


In [21]:
gradient = torch.randn(2, 2)

# this would fail if we didn't specify
# that we want to retain variables
y.backward(gradient)

print(x.grad)

tensor([[-0.9810,  1.1249],
        [ 2.6429,  2.0380]])


In [22]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
